# Generated by Django 5.2.5 on 2025-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=11)),
                ("address", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("cnc_file", models.FileField(upload_to="cnc_files/")),
                ("material", models.CharField(max_length=50)),
                ("thickness", models.IntegerField()),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estimated_time",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Quote"),
                            ("quoted", "Quoted"),
                            ("confirmed", "Confirmed"),
                            ("paid", "Paid"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "receipt_code",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
