# Generated by Django 5.2.5 on 2025-09-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="material",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="receipt_code",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="thickness",
            field=models.CharField(max_length=10),
        ),
    ]
