# Generated by Django 5.2.5 on 2025-09-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_material_alter_order_receipt_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="receipt_code",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Quoted", "Quoted"),
                    ("Paid", "Paid"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
