# Generated by Django 5.2.5 on 2025-09-06 20:02

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_receipt_code_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="estimated_time",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="receipt_code",
            field=models.CharField(
                default=orders.models.generate_receipt_code, max_length=8, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
