# Generated by Django 5.2.5 on 2025-09-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_estimated_time_alter_order_receipt_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PA', 'در انتظار ادمین'), ('PP', 'در انتظار پرداخت'), ('AC', 'تایید شده'), ('CL', 'لغو شده')], default='PA', max_length=2),
        ),
    ]
