# Generated by Django 5.2.5 on 2025-09-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PA', 'Pending of admin'), ('PP', 'Pending of payment'), ('AC', 'Accepted'), ('CL', 'Cancelled')], default='PA', max_length=2),
        ),
    ]
